---
title: "hw week 8 rmarkdown"
author: "Kriste Lee"
date: "March 7, 2017"
output: html_document
---

```{r}
library(ggplot2)

setwd("/home/eeb177-student/Desktop/eeb-177/homework/") #you will need to change this to match your directory!
canids <- read.csv("/home/eeb177-student/Desktop/eeb-177/homework/canids/sorted_canid_ranges.csv", header = F, as.is = T)
names(canids) <- c("genus", "species", "minage", "maxage")
head(canids)

```

```{r}

canid_occ <- ggplot(canids, aes( species, ymin = maxage, ymax=minage, colour = genus))
canid_occ <- canid_occ + geom_linerange()
canid_occ

```


```{r}

canid_occ <- canid_occ + theme(legend.position="none")
canid_occ

```
```{r}
canid_occ <- canid_occ + coord_flip()
canid_occ
```


```{r}
canid_occ <- canid_occ +  theme(axis.text.y = element_text(size=3))
canid_occ


```
```{r}
canid_occ <- canid_occ + theme(axis.ticks.y=element_blank())
canid_occ
```


```{r}

canid_occ <- canid_occ + scale_y_continuous(limits=c(0, 40), expand = c(0, 0), breaks=c(0, 10, 20, 30, 40))
canid_occ

```

```{r}
canid_occ <- canid_occ + labs(title = "Canid Fossil Occurrences", x = "Species", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20))
canid_occ
```
```{r}
ggsave(filename = "canid-occ.pdf", plot = canid_occ)

```


Questions:
1.Canids
2.211 different occurances of species
3.65 different genera
`eeb177-student@eeb177-VirtualBox:~/Desktop/eeb-177/homework/canids$ cut -f1 -d " " sorted_canid_ranges.csv | uniq -c | wc -l`
4. based on the pdf image Metalopex merriami

